### ISSUE TITLE
Calling Binary Eye from other apps stopped working

### ISSUE THREAD

**Issue by di72nn** [markusfisch/BinaryEye#84]
Starting from 1.17.0 calling Binary Eye [this way](https://stackoverflow.com/a/8833123) stopped working - Binary Eye just shows [the usual result form](https://raw.githubusercontent.com/markusfisch/BinaryEye/gh-pages/screencap-decoded.png) instead of returning the result.

**Comment by markusfisch** [comment]
Oh, sorry, that was my fault 🙈 Fixed in https://github.com/markusfisch/BinaryEye/commit/7416037762a290298be30fffc37060225b02f44b

Version 1.18.0 should become available in the next few hours on Google Play.

Or fetch the APK directly from here: https://github.com/markusfisch/BinaryEye/releases

**Comment by di72nn** [comment]
Thanks for the quick fix! Also thank you for developing the app - Binary Eye is my go-to QR reader :)

**Comment by di72nn** [comment]
The problem still seem to be present. `1.16.0` is the latest version that is working for me.
